### ISSUE TITLE
Notifications not being sent to slack

### ISSUE THREAD

**Issue by maria-reynoso** [chaostoolkit-incubator/chaostoolkit-slack#9]
Hi, I'm trying to send notifications to slack when an experiment starts, ends, fails, etc. I installed chaostoolkit-slack on my kubernetes environment (using the chaos toolkit kubernetes operator). When I run an experiment, I don't get any notification on slack and I don't see any error in the logs either. 

This is my setttings.yaml file:

```notifications:
 -
  type: plugin
  module: chaosslack.notification
  token: xoxb-xxxxxxxxxxx
  channel: chaos-toolkit
```

I don't think it's an issue with the kubernetes operator, as I've also installed it locally. Do I need to do more configurations? 
I test the slack token and it works fine, I also tried using the notifications type: `http`

Thanks

**Comment by dmartin35** [comment]
Hi @maria-reynoso 

Your issue might be fixed by this change https://github.com/chaostoolkit-incubator/chaostoolkit-slack/pull/10
However, I ran into slack permissions issues, I don't know if it might not be your case as well

The token needs to have the `chat:write:bot` scope.

If this does not work yet, could you try running the `chaos` command in verbose mode : `chaos --verbose  run ...`

**Comment by maria-reynoso** [comment]
Hi @dmartin35 sorry this issue can be closed, as indeed it was fixed by that change. 

Thanks!
